dist: trusty
language: python
install: |
    pip install pyyaml
script: |
  set -e
  for x in `git diff --name-only $TRAVIS_COMMIT_RANGE | grep .sh`; do
    echo Linting $x
    scripts/lint-recipes $x
  done
