package: GEANT4
version: v4.10.01.p02-alice1
source: https://github.com/alisw/geant4
tag: c61ed5a54780a8da922ccf199ca69592189c7e66
---
#!/bin/bash -e

cmake $SOURCEDIR \
  -DCMAKE_CXX_FLAGS="-fPIC" \
  -DCMAKE_INSTALL_PREFIX:PATH="$INSTALLROOT" \
  -DCMAKE_INSTALL_LIBDIR="lib" \
  -DCMAKE_BUILD_TYPE=RelWithDebInfo \
  -DGEANT4_BUILD_TLS_MODEL:STRING="global-dynamic" \
  -DGEANT4_ENABLE_TESTING=OFF \
  -DBUILD_SHARED_LIBS=ON \
  -DGEANT4_INSTALL_EXAMPLES=OFF \
  -DCLHEP_ROOT_DIR:PATH="$CLHEP_ROOT" \
  -DGEANT4_BUILD_MULTITHREADED=ON \
  -DCMAKE_STATIC_LIBRARY_CXX_FLAGS="-fPIC" \
  -DCMAKE_STATIC_LIBRARY_C_FLAGS="-fPIC" \
  -DGEANT4_USE_G3TOG4=ON \
  -DGEANT4_INSTALL_DATA=ON \
  -DGEANT4_USE_SYSTEM_EXPAT=OFF

make ${JOBS+-j $JOBS}
make install
