name: QCG Jenkins RPM Trigger Job

on:
  push:
    branches:
      - master
    paths:
      - 'qcg.sh'

jobs:
  trigger_jenkins_for_qcg:
    runs-on: macOS-10.14
    steps:
      - run: brew remove curl
      - run: |
          ARCHITECTURE=slc8_x86-64
          DEFAULTS=o2-dataflow
          PACKAGE_NAME=qcg
          echo "${{ secrets.KERBEROS_PASSWORD }}" | kinit "${{ secrets.KERBEROS_USERNAME }}@${{ secrets.KERBEROS_HOSTNAME }}"
          curl -X POST  \
            -k \
            --anyauth \
            -u : https://${{ secrets.ALIJENKINS_HOSTNAME }}/kerberos/job/build-any-ib/buildWithParameters \
            -H 'Content-Type: application/x-www-form-urlencoded' \
            -d 'PACKAGE_NAME=$PACKAGE_NAME&DEFAULTS=$DEFAULTS&ARCHITECTURE=$ARCHITECTURE' \
